import {
  AmendLastCommit,
  CheckoutBranch,
  Commit,
  CreateBranch,
  DeleteBranch,
  Diff,
  Discard,
  Fetch,
  GetBranch,
  GetGraph,
  GetLog,
  Init,
  IsRepo,
  ListBranches,
  ListRemotes,
  Pull,
  Push,
  SetWorkdir,
  ShowAtHead,
  Stage,
  StageAll,
  StashDrop,
  StashList,
  StashPop,
  StashSave,
  Status,
  UndoLastCommit,
  Unstage,
} from "../../../wailsjs/go/main/Git";
import {
  CancelDeviceFlow,
  CreateAndPublish,
  GetUser,
  IsAuthenticated,
  Logout,
  PollDeviceToken,
  StartDeviceFlow,
} from "../../../wailsjs/go/main/GitHub";
import { on } from "@/rpc/core";
import type {
  DeviceFlowStart,
  GitBranch,
  GitChangedFile,
  GitCommit,
  GitGraphNode,
  GitHubRepo,
  GitHubUser,
  GitRemote,
  GitStash,
} from "./types";

export const rpc = {
  git: {
    setWorkdir: (path: string) => SetWorkdir(path),
    status: () => Status() as Promise<GitChangedFile[]>,
    diff: (path: string, staged: boolean) => Diff(path, staged),
    showAtHead: (path: string) => ShowAtHead(path) as Promise<string>,
    stage: (path: string) => Stage(path),
    unstage: (path: string) => Unstage(path),
    stageAll: () => StageAll(),
    discardFile: (path: string) => Discard(path),
    commit: (message: string) => Commit(message),
    push: () => Push(),
    pull: () => Pull(),
    fetch: () => Fetch(),
    getBranch: () => GetBranch() as Promise<string>,
    listBranches: () => ListBranches() as Promise<GitBranch[]>,
    getLog: (limit: number) => GetLog(limit) as Promise<GitCommit[]>,
    isRepo: () => IsRepo() as Promise<boolean>,
    init: () => Init(),
    createBranch: (name: string) => CreateBranch(name),
    checkoutBranch: (name: string) => CheckoutBranch(name),
    deleteBranch: (name: string, force: boolean) => DeleteBranch(name, force),
    stashSave: (message: string) => StashSave(message),
    stashList: () => StashList() as Promise<GitStash[]>,
    stashPop: (index: number) => StashPop(index),
    stashDrop: (index: number) => StashDrop(index),
    undoLastCommit: () => UndoLastCommit(),
    amendLastCommit: (message: string) => AmendLastCommit(message),
    listRemotes: () => ListRemotes() as Promise<GitRemote[]>,
    getGraph: (limit: number) => GetGraph(limit) as Promise<GitGraphNode[]>,
  },
  github: {
    startDeviceFlow: () => StartDeviceFlow() as Promise<DeviceFlowStart>,
    pollDeviceToken: (deviceCode: string, interval: number) =>
      PollDeviceToken(deviceCode, interval),
    cancelDeviceFlow: () => CancelDeviceFlow(),
    isAuthenticated: () => IsAuthenticated() as Promise<boolean>,
    getUser: () => GetUser() as Promise<GitHubUser>,
    logout: () => Logout(),
    createAndPublish: (name: string, priv: boolean) =>
      CreateAndPublish(name, priv) as Promise<GitHubRepo>,
  },
  on,
};
