import {
  AmendLastCommit,
  CheckoutBranch,
  Commit,
  CreateBranch,
  DeleteBranch,
  Diff,
  Discard,
  Fetch,
  GetBranch,
  GetGraph,
  GetLog,
  Init,
  IsRepo,
  ListBranches,
  ListRemotes,
  Pull,
  Push,
  SetWorkdir,
  Stage,
  StageAll,
  StashDrop,
  StashList,
  StashPop,
  StashSave,
  Status,
  UndoLastCommit,
  Unstage,
} from "../../../wailsjs/go/main/Git";
import { on } from "@/rpc/core";
import type { GitBranch, GitChangedFile, GitCommit, GitGraphNode, GitRemote, GitStash } from "./types";

export const rpc = {
  git: {
    setWorkdir: (path: string) => SetWorkdir(path),
    status: () => Status() as Promise<GitChangedFile[]>,
    diff: (path: string, staged: boolean) => Diff(path, staged),
    stage: (path: string) => Stage(path),
    unstage: (path: string) => Unstage(path),
    stageAll: () => StageAll(),
    discardFile: (path: string) => Discard(path),
    commit: (message: string) => Commit(message),
    push: () => Push(),
    pull: () => Pull(),
    fetch: () => Fetch(),
    getBranch: () => GetBranch() as Promise<string>,
    listBranches: () => ListBranches() as Promise<GitBranch[]>,
    getLog: (limit: number) => GetLog(limit) as Promise<GitCommit[]>,
    isRepo: () => IsRepo() as Promise<boolean>,
    init: () => Init(),
    createBranch: (name: string) => CreateBranch(name),
    checkoutBranch: (name: string) => CheckoutBranch(name),
    deleteBranch: (name: string, force: boolean) => DeleteBranch(name, force),
    stashSave: (message: string) => StashSave(message),
    stashList: () => StashList() as Promise<GitStash[]>,
    stashPop: (index: number) => StashPop(index),
    stashDrop: (index: number) => StashDrop(index),
    undoLastCommit: () => UndoLastCommit(),
    amendLastCommit: (message: string) => AmendLastCommit(message),
    listRemotes: () => ListRemotes() as Promise<GitRemote[]>,
    getGraph: (limit: number) => GetGraph(limit) as Promise<GitGraphNode[]>,
  },
  on,
};
