// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProductInfo() {
  return window['go']['main']['About']['GetProductInfo']();
}

export function OpenUrl(arg1) {
  return window['go']['main']['About']['OpenUrl'](arg1);
}
