// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function OpenFolderDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<void>;

export function ReplaceInFiles(arg1:string,arg2:main.SearchOptions,arg3:string):Promise<number>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<main.FileEntry>>;

export function SearchInFiles(arg1:string,arg2:main.SearchOptions):Promise<Array<main.SearchMatch>>;

export function WatchRoot(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
