// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SearchInFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2);
}

export function WatchRoot(arg1) {
  return window['go']['main']['App']['WatchRoot'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
