// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['main']['CommandCenter']['Execute'](arg1);
}

export function GetWorkspaceRoots() {
  return window['go']['main']['CommandCenter']['GetWorkspaceRoots']();
}

export function GotoLine(arg1, arg2) {
  return window['go']['main']['CommandCenter']['GotoLine'](arg1, arg2);
}

export function List(arg1, arg2) {
  return window['go']['main']['CommandCenter']['List'](arg1, arg2);
}

export function ListAllFiles() {
  return window['go']['main']['CommandCenter']['ListAllFiles']();
}

export function OpenFile(arg1) {
  return window['go']['main']['CommandCenter']['OpenFile'](arg1);
}

export function SetWorkdir(arg1) {
  return window['go']['main']['CommandCenter']['SetWorkdir'](arg1);
}
