// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Execute(arg1:string):Promise<void>;

export function GetWorkspaceRoots():Promise<Array<main.CmdFileEntry>>;

export function GotoLine(arg1:number,arg2:number):Promise<void>;

export function List(arg1:string,arg2:string):Promise<Array<main.PaletteItem>>;

export function ListAllFiles():Promise<Array<main.CmdFileEntry>>;

export function OpenFile(arg1:string):Promise<void>;

export function SetWorkdir(arg1:string):Promise<void>;
