// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachWorkspace(arg1) {
  return window['go']['main']['Config']['AttachWorkspace'](arg1);
}

export function Get(arg1, arg2) {
  return window['go']['main']['Config']['Get'](arg1, arg2);
}

export function GetMany(arg1) {
  return window['go']['main']['Config']['GetMany'](arg1);
}

export function OpenSettingsJson() {
  return window['go']['main']['Config']['OpenSettingsJson']();
}

export function Reset(arg1) {
  return window['go']['main']['Config']['Reset'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['main']['Config']['Set'](arg1, arg2);
}
