// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachWorkspace(arg1:main.WorkspaceConfig):Promise<void>;

export function Get(arg1:string,arg2:any):Promise<any>;

export function GetMany(arg1:Array<main.ConfigQuery>):Promise<Array<any>>;

export function OpenSettingsJson():Promise<void>;

export function Reset(arg1:string):Promise<void>;

export function Set(arg1:string,arg2:any):Promise<void>;
