// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2) {
  return window['go']['main']['Git']['AddRemote'](arg1, arg2);
}

export function AmendLastCommit(arg1) {
  return window['go']['main']['Git']['AmendLastCommit'](arg1);
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['Git']['CheckoutBranch'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['Git']['Commit'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['Git']['CreateBranch'](arg1);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['Git']['DeleteBranch'](arg1, arg2);
}

export function Diff(arg1, arg2) {
  return window['go']['main']['Git']['Diff'](arg1, arg2);
}

export function Discard(arg1) {
  return window['go']['main']['Git']['Discard'](arg1);
}

export function Fetch() {
  return window['go']['main']['Git']['Fetch']();
}

export function GetBranch() {
  return window['go']['main']['Git']['GetBranch']();
}

export function GetGraph(arg1) {
  return window['go']['main']['Git']['GetGraph'](arg1);
}

export function GetLog(arg1) {
  return window['go']['main']['Git']['GetLog'](arg1);
}

export function HasCommits() {
  return window['go']['main']['Git']['HasCommits']();
}

export function Init() {
  return window['go']['main']['Git']['Init']();
}

export function IsRepo() {
  return window['go']['main']['Git']['IsRepo']();
}

export function ListBranches() {
  return window['go']['main']['Git']['ListBranches']();
}

export function ListRemotes() {
  return window['go']['main']['Git']['ListRemotes']();
}

export function Pull() {
  return window['go']['main']['Git']['Pull']();
}

export function Push() {
  return window['go']['main']['Git']['Push']();
}

export function SetWorkdir(arg1) {
  return window['go']['main']['Git']['SetWorkdir'](arg1);
}

export function Stage(arg1) {
  return window['go']['main']['Git']['Stage'](arg1);
}

export function StageAll() {
  return window['go']['main']['Git']['StageAll']();
}

export function StashDrop(arg1) {
  return window['go']['main']['Git']['StashDrop'](arg1);
}

export function StashList() {
  return window['go']['main']['Git']['StashList']();
}

export function StashPop(arg1) {
  return window['go']['main']['Git']['StashPop'](arg1);
}

export function StashSave(arg1) {
  return window['go']['main']['Git']['StashSave'](arg1);
}

export function Status() {
  return window['go']['main']['Git']['Status']();
}

export function UndoLastCommit() {
  return window['go']['main']['Git']['UndoLastCommit']();
}

export function Unstage(arg1) {
  return window['go']['main']['Git']['Unstage'](arg1);
}
