// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AmendLastCommit(arg1:string):Promise<void>;

export function CheckoutBranch(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function Diff(arg1:string,arg2:boolean):Promise<string>;

export function Discard(arg1:string):Promise<void>;

export function Fetch():Promise<void>;

export function GetBranch():Promise<string>;

export function GetGraph(arg1:number):Promise<Array<main.GitGraphNode>>;

export function GetLog(arg1:number):Promise<Array<main.GitCommit>>;

export function Init():Promise<void>;

export function IsRepo():Promise<boolean>;

export function ListBranches():Promise<Array<main.GitBranch>>;

export function ListRemotes():Promise<Array<main.GitRemote>>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function SetWorkdir(arg1:string):Promise<void>;

export function Stage(arg1:string):Promise<void>;

export function StageAll():Promise<void>;

export function StashDrop(arg1:number):Promise<void>;

export function StashList():Promise<Array<main.GitStash>>;

export function StashPop(arg1:number):Promise<void>;

export function StashSave(arg1:string):Promise<void>;

export function Status():Promise<Array<main.GitChangedFile>>;

export function UndoLastCommit():Promise<void>;

export function Unstage(arg1:string):Promise<void>;
