// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDeviceFlow() {
  return window['go']['main']['GitHub']['CancelDeviceFlow']();
}

export function CreateAndPublish(arg1, arg2) {
  return window['go']['main']['GitHub']['CreateAndPublish'](arg1, arg2);
}

export function GetUser() {
  return window['go']['main']['GitHub']['GetUser']();
}

export function IsAuthenticated() {
  return window['go']['main']['GitHub']['IsAuthenticated']();
}

export function Logout() {
  return window['go']['main']['GitHub']['Logout']();
}

export function PollDeviceToken(arg1, arg2) {
  return window['go']['main']['GitHub']['PollDeviceToken'](arg1, arg2);
}

export function StartDeviceFlow() {
  return window['go']['main']['GitHub']['StartDeviceFlow']();
}
