// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDeviceFlow():Promise<void>;

export function CreateAndPublish(arg1:string,arg2:boolean):Promise<main.GitHubRepo>;

export function GetUser():Promise<main.GitHubUser>;

export function IsAuthenticated():Promise<boolean>;

export function Logout():Promise<void>;

export function PollDeviceToken(arg1:string,arg2:number):Promise<void>;

export function StartDeviceFlow():Promise<main.DeviceFlowStart>;
