// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClientID():Promise<string>;

export function GetMe():Promise<main.LinearUser>;

export function GetMyIssues():Promise<Array<main.LinearIssue>>;

export function IsAuthenticated():Promise<boolean>;

export function Logout():Promise<void>;

export function SetClientID(arg1:string):Promise<void>;

export function StartOAuth():Promise<void>;
