// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientID() {
  return window['go']['main']['Linear']['GetClientID']();
}

export function GetMe() {
  return window['go']['main']['Linear']['GetMe']();
}

export function GetMyIssues() {
  return window['go']['main']['Linear']['GetMyIssues']();
}

export function IsAuthenticated() {
  return window['go']['main']['Linear']['IsAuthenticated']();
}

export function Logout() {
  return window['go']['main']['Linear']['Logout']();
}

export function SetClientID(arg1) {
  return window['go']['main']['Linear']['SetClientID'](arg1);
}

export function StartOAuth() {
  return window['go']['main']['Linear']['StartOAuth']();
}
