// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLSPPort():Promise<number>;

export function GetLSPStatus():Promise<Array<main.LSPServerStatus>>;

export function InstallLSPServer(arg1:string):Promise<void>;

export function ListAvailableLSP():Promise<Record<string, string>>;
