// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLSPPort() {
  return window['go']['main']['LSP']['GetLSPPort']();
}

export function GetLSPStatus() {
  return window['go']['main']['LSP']['GetLSPStatus']();
}

export function InstallLSPServer(arg1) {
  return window['go']['main']['LSP']['InstallLSPServer'](arg1);
}

export function ListAvailableLSP() {
  return window['go']['main']['LSP']['ListAvailableLSP']();
}
