// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['Spotify']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['Spotify']['Disconnect']();
}

export function GetAccessToken() {
  return window['go']['main']['Spotify']['GetAccessToken']();
}

export function IsConnected() {
  return window['go']['main']['Spotify']['IsConnected']();
}

export function Status() {
  return window['go']['main']['Spotify']['Status']();
}
