// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect():Promise<string>;

export function Disconnect():Promise<void>;

export function GetAccessToken():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Status():Promise<main.SpotifyAuthStatus>;
