// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function List():Promise<Array<main.TaskDef>>;

export function Run(arg1:string):Promise<string>;

export function SetWorkdir(arg1:string):Promise<void>;
