// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List() {
  return window['go']['main']['Tasks']['List']();
}

export function Run(arg1) {
  return window['go']['main']['Tasks']['Run'](arg1);
}

export function SetWorkdir(arg1) {
  return window['go']['main']['Tasks']['SetWorkdir'](arg1);
}
