// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePty(arg1) {
  return window['go']['main']['Terminal']['ClosePty'](arg1);
}

export function GetDefaultShell() {
  return window['go']['main']['Terminal']['GetDefaultShell']();
}

export function GetPty(arg1) {
  return window['go']['main']['Terminal']['GetPty'](arg1);
}

export function ListPty() {
  return window['go']['main']['Terminal']['ListPty']();
}

export function ListShells() {
  return window['go']['main']['Terminal']['ListShells']();
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['Terminal']['ResizePty'](arg1, arg2, arg3);
}

export function SetDefaultShell(arg1) {
  return window['go']['main']['Terminal']['SetDefaultShell'](arg1);
}

export function ShellInitScript(arg1) {
  return window['go']['main']['Terminal']['ShellInitScript'](arg1);
}

export function StartPty(arg1, arg2, arg3) {
  return window['go']['main']['Terminal']['StartPty'](arg1, arg2, arg3);
}

export function StartPtyWith(arg1) {
  return window['go']['main']['Terminal']['StartPtyWith'](arg1);
}

export function WritePty(arg1, arg2) {
  return window['go']['main']['Terminal']['WritePty'](arg1, arg2);
}

export function WritePtyB64(arg1, arg2) {
  return window['go']['main']['Terminal']['WritePtyB64'](arg1, arg2);
}
