// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClosePty(arg1:string):Promise<void>;

export function GetDefaultShell():Promise<string>;

export function GetPty(arg1:string):Promise<main.SessionInfo>;

export function ListPty():Promise<Array<main.SessionInfo>>;

export function ListShells():Promise<Array<main.ShellInfo>>;

export function ResizePty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetDefaultShell(arg1:string):Promise<void>;

export function ShellInitScript(arg1:string):Promise<string>;

export function StartPty(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StartPtyWith(arg1:main.StartOptions):Promise<string>;

export function WritePty(arg1:string,arg2:string):Promise<void>;

export function WritePtyB64(arg1:string,arg2:string):Promise<void>;
