// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1, arg2) {
  return window['go']['main']['WorkspaceConfig']['Get'](arg1, arg2);
}

export function GetMany(arg1) {
  return window['go']['main']['WorkspaceConfig']['GetMany'](arg1);
}

export function Lookup(arg1) {
  return window['go']['main']['WorkspaceConfig']['Lookup'](arg1);
}

export function OpenSettingsJson() {
  return window['go']['main']['WorkspaceConfig']['OpenSettingsJson']();
}

export function Reset(arg1) {
  return window['go']['main']['WorkspaceConfig']['Reset'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['main']['WorkspaceConfig']['Set'](arg1, arg2);
}

export function SetWorkdir(arg1) {
  return window['go']['main']['WorkspaceConfig']['SetWorkdir'](arg1);
}
